import React from 'react'

import { Helmet } from 'react-helmet'

import Navbar8 from '../components/navbar8'
import ChatEnvironment from '../components/chat-environment'
import './vgen.css'

const VGEN = (props) => {
  return (
    <div className="vgen-container">
      <Helmet>
        <title>VGEN - Character NFT template3</title>
        <meta property="og:title" content="VGEN - Character NFT template3" />
      </Helmet>
      <Navbar8
        text={
          <fragment>
            <span className="vgen-text">Account</span>
          </fragment>
        }
        view={
          <fragment>
            <span className="vgen-text01">+ NEW </span>
          </fragment>
        }
        link1={
          <fragment>
            <span className="vgen-text02 thq-link thq-body-small">Link 1</span>
          </fragment>
        }
        link2={
          <fragment>
            <span className="vgen-text03 thq-link thq-body-small">Link 2</span>
          </fragment>
        }
        link3={
          <fragment>
            <span className="vgen-text04 thq-link thq-body-small">Link 3</span>
          </fragment>
        }
        link4={
          <fragment>
            <span className="vgen-text05 thq-link thq-body-small">Link 4</span>
          </fragment>
        }
        page1={
          <fragment>
            <span className="vgen-text06 thq-body-large">Page One</span>
          </fragment>
        }
        page2={
          <fragment>
            <span className="vgen-text07 thq-body-large">Page Two</span>
          </fragment>
        }
        page3={
          <fragment>
            <span className="vgen-text08 thq-body-large">Page Three</span>
          </fragment>
        }
        page4={
          <fragment>
            <span className="vgen-text09 thq-body-large">Page Four</span>
          </fragment>
        }
        action1={
          <fragment>
            <span className="vgen-text10">Main Action</span>
          </fragment>
        }
        action2={
          <fragment>
            <span className="vgen-text11">Secondary Action</span>
          </fragment>
        }
        rootClassName="navbar8-root-class-name1"
        page1Description={
          <fragment>
            <span className="vgen-text12 thq-body-small">
              Page One Description
            </span>
          </fragment>
        }
        page2Description={
          <fragment>
            <span className="vgen-text13 thq-body-small">
              Page Two Description
            </span>
          </fragment>
        }
        page3Description={
          <fragment>
            <span className="vgen-text14 thq-body-small">
              Page Three Description
            </span>
          </fragment>
        }
        page4Description={
          <fragment>
            <span className="vgen-text15 thq-body-small">
              Page Four Description
            </span>
          </fragment>
        }
      ></Navbar8>
      <ChatEnvironment
        text2={
          <fragment>
            <span className="vgen-text16 form-option">Text</span>
          </fragment>
        }
        text3={
          <fragment>
            <span className="vgen-text17">
              This is a placeholder for the caption that will be generated by
              OpenAI for the Generated video
            </span>
          </fragment>
        }
        button={
          <fragment>
            <span className="vgen-text18">GENERATE</span>
          </fragment>
        }
        text31={
          <fragment>
            <span className="vgen-text19">
              This is a placeholder for the caption that will be generated by
              OpenAI for the Generated video
            </span>
          </fragment>
        }
        button2={
          <fragment>
            <span className="vgen-text20">DOWNLOAD</span>
          </fragment>
        }
        header31={
          <fragment>
            <span className="vgen-text21 ai-word">DESCRIBE</span>
          </fragment>
        }
        heading3={
          <fragment>
            <span className="vgen-text22 Form-titles">VIDEO CAPTION</span>
          </fragment>
        }
        heading4={
          <fragment>
            <span className="vgen-text23 Form-titles">VIDEO DETAILS</span>
          </fragment>
        }
        header312={
          <fragment>
            <span className="vgen-text24 ai-word">DOWNLOAD</span>
          </fragment>
        }
        header1111={
          <fragment>
            <span className="vgen-text25">Video in DETAIL</span>
          </fragment>
        }
        header11112={
          <fragment>
            <span className="vgen-text26">&amp; Publish Video</span>
          </fragment>
        }
        rootClassName="chat-environment-root-class-name1"
        heading21={
          <fragment>
            <span className="vgen-text27 Form-titles">Audio Settings</span>
          </fragment>
        }
        heading11={
          <fragment>
            <span className="vgen-text28 Form-titles">Video Settings</span>
          </fragment>
        }
      ></ChatEnvironment>
      <div className="vgen-container1"></div>
      <div className="vgen-container2"></div>
    </div>
  )
}

export default VGEN
